# 08 - Save Final Models

## Objective

The purpose of this notebook is to save the best-performing machine
learning model for each health risk score based on the results from
the Model Evaluation notebook.

The selected models are:

- Diabetes Risk Score → Linear Regression
- Hypertension Risk Score → Ridge Regression
- Heart Disease Risk Score → Gradient Boosting
- Obesity Risk Score → Gradient Boosting
- Cholesterol Risk Score → Gradient Boosting

The final models will be saved for use in the prediction pipeline.

This notebook does not retrain the models.

It only selects and saves the already-trained models identified during
model evaluation.

In [1]:
import pandas as pd
import numpy as np
import joblib
import os

In [2]:
#Create final model directory

final_model_dir = "../models/final"

os.makedirs(
    final_model_dir,
    exist_ok=True
)

print("Final model directory:", final_model_dir)

Final model directory: ../models/final

In [3]:
#Define the selected models

best_model_selection = {
    "diabetes_risk_score": "Linear Regression",
    "hypertension_risk_score": "Ridge Regression",
    "heart_disease_risk_score": "Gradient Boosting",
    "obesity_risk_score": "Gradient Boosting",
    "cholesterol_risk_score": "Gradient Boosting"
}

best_model_selection

#Display the model selection

print("Final Model Selection")

for target, model_name in best_model_selection.items():
    print(f"{target:30} → {model_name}")

Final Model Selection
diabetes_risk_score            → Linear Regression
hypertension_risk_score        → Ridge Regression
heart_disease_risk_score       → Gradient Boosting
obesity_risk_score             → Gradient Boosting
cholesterol_risk_score         → Gradient Boosting

In [4]:
#Load candidate models

candidate_model_dir = "../models/candidates"

candidate_model_files = {
    "Linear Regression": "linear_regression.pkl",
    "Ridge Regression": "ridge_regression.pkl",
    "Random Forest": "random_forest.pkl",
    "Gradient Boosting": "gradient_boosting.pkl",
    "Extra Trees": "extra_trees.pkl"
}

#Load all candidate models

candidate_models = {}

for model_name, file_name in candidate_model_files.items():

    file_path = os.path.join(
        candidate_model_dir,
        file_name
    )

    candidate_models[model_name] = joblib.load(
        file_path
    )

    print(f"{model_name} loaded successfully.")

#Verify candidate models

print("\nAvailable Candidate Models")

for model_name in candidate_models:
    print( model_name)

Linear Regression loaded successfully.
Ridge Regression loaded successfully.
Random Forest loaded successfully.
Gradient Boosting loaded successfully.
Extra Trees loaded successfully.

Available Candidate Models
- Linear Regression
- Ridge Regression
- Random Forest
- Gradient Boosting
- Extra Trees

In [5]:
#Load evaluation results

evaluation_df = pd.read_csv(
    "../outputs/metrics/model_evaluation_results.csv"
)

evaluation_df.head()

               Model                    Target       MAE      RMSE        R2
0  Linear Regression       diabetes_risk_score  1.714473  2.170258  0.961087
1  Linear Regression   hypertension_risk_score  2.018996  2.533214  0.960430
2  Linear Regression  heart_disease_risk_score  4.149555  5.184019  0.887281
3  Linear Regression        obesity_risk_score  1.373976  1.771350  0.974381
4  Linear Regression    cholesterol_risk_score  1.165006  1.503186  0.986829

In [6]:
#Load best-model summary

best_models_df = pd.read_csv(
    "../outputs/metrics/best_models_by_target.csv",
    index_col=0
)

best_models_df

                                      Model       MAE      RMSE        R2
diabetes_risk_score       Linear Regression  1.714473  2.170258  0.961087
hypertension_risk_score    Ridge Regression  2.018995  2.533213  0.960430
heart_disease_risk_score  Gradient Boosting  3.292623  4.178837  0.926755
obesity_risk_score        Gradient Boosting  1.267963  1.592833  0.979284
cholesterol_risk_score    Gradient Boosting  0.930187  1.173354  0.991975

In [7]:
#Verify selection against our expected results

for target, expected_model in best_model_selection.items():

    actual_model = best_models_df.loc[
        target,
        "Model"
    ]

    if actual_model != expected_model:

        raise ValueError(
            f"Model mismatch for {target}: "
            f"expected {expected_model}, "
            f"found {actual_model}"
        )

print("Model selection verified successfully.")

Model selection verified successfully.

In [8]:
#Understand the target indexes

target_columns = [
    "diabetes_risk_score",
    "hypertension_risk_score",
    "heart_disease_risk_score",
    "obesity_risk_score",
    "cholesterol_risk_score"
]

target_indices = {
    target: index
    for index, target in enumerate(target_columns)
}

target_indices

{'diabetes_risk_score': 0,
 'hypertension_risk_score': 1,
 'heart_disease_risk_score': 2,
 'obesity_risk_score': 3,
 'cholesterol_risk_score': 4}

In [9]:
#Save the final models

final_models = {}

for target, model_name in best_model_selection.items():

    model = candidate_models[model_name]

    final_models[target] = model

    print(
        f"{target} → {model_name}"
    )

diabetes_risk_score → Linear Regression
hypertension_risk_score → Ridge Regression
heart_disease_risk_score → Gradient Boosting
obesity_risk_score → Gradient Boosting
cholesterol_risk_score → Gradient Boosting

In [10]:
#Save each final model

for target, model in final_models.items():

    model_path = os.path.join(
        final_model_dir,
        f"{target.replace('_risk_score', '')}_model.pkl"
    )

    joblib.dump(
        model,
        model_path
    )

    print(
        f"Saved: {model_path}"
    )

Saved: ../models/final\diabetes_model.pkl
Saved: ../models/final\hypertension_model.pkl
Saved: ../models/final\heart_disease_model.pkl
Saved: ../models/final\obesity_model.pkl
Saved: ../models/final\cholesterol_model.pkl

In [11]:
#Important: Save target/model mapping

final_model_info = {}

for target, model_name in best_model_selection.items():

    final_model_info[target] = {
        "model_name": model_name,
        "target_index": target_indices[target],
        "model_file": (
            f"{target.replace('_risk_score', '')}_model.pkl"
        )
    }

final_model_info

{'diabetes_risk_score': {'model_name': 'Linear Regression',
  'target_index': 0,
  'model_file': 'diabetes_model.pkl'},
 'hypertension_risk_score': {'model_name': 'Ridge Regression',
  'target_index': 1,
  'model_file': 'hypertension_model.pkl'},
 'heart_disease_risk_score': {'model_name': 'Gradient Boosting',
  'target_index': 2,
  'model_file': 'heart_disease_model.pkl'},
 'obesity_risk_score': {'model_name': 'Gradient Boosting',
  'target_index': 3,
  'model_file': 'obesity_model.pkl'},
 'cholesterol_risk_score': {'model_name': 'Gradient Boosting',
  'target_index': 4,
  'model_file': 'cholesterol_model.pkl'}}

In [12]:
#Save model information

joblib.dump(
    final_model_info,
    "../models/final_model_info.pkl"
)

print("Final model information saved successfully.")

Final model information saved successfully.

In [13]:
#preprocessing pipeline

preprocessing_path = "../models/preprocessing_pipeline.pkl"

if os.path.exists(preprocessing_path):

    print(
        "Preprocessing pipeline found successfully."
    )

else:

    print(
        "WARNING: preprocessing_pipeline.pkl was not found."
    )

Preprocessing pipeline found successfully.

In [14]:
#Verify final models exist

print("Final Models")
print("=" * 50)

for target, info in final_model_info.items():

    path = os.path.join(
        final_model_dir,
        info["model_file"]
    )

    if os.path.exists(path):

        print(
            f"✓ {target}: {info['model_file']}"
        )

    else:

        print(
            f"✗ Missing: {target}"
        )

Final Models
==================================================
✓ diabetes_risk_score: diabetes_model.pkl
✓ hypertension_risk_score: hypertension_model.pkl
✓ heart_disease_risk_score: heart_disease_model.pkl
✓ obesity_risk_score: obesity_model.pkl
✓ cholesterol_risk_score: cholesterol_model.pkl

In [15]:
#Load the saved final models

loaded_final_models = {}

for target, info in final_model_info.items():

    model_path = os.path.join(
        final_model_dir,
        info["model_file"]
    )

    loaded_final_models[target] = joblib.load(
        model_path
    )

    print(
        f"{target} loaded successfully."
    )

diabetes_risk_score loaded successfully.
hypertension_risk_score loaded successfully.
heart_disease_risk_score loaded successfully.
obesity_risk_score loaded successfully.
cholesterol_risk_score loaded successfully.

In [16]:
#Verify model types

for target, model in loaded_final_models.items():

    print(
        f"{target}: {type(model).__name__}"
    )

diabetes_risk_score: LinearRegression
hypertension_risk_score: Ridge
heart_disease_risk_score: MultiOutputRegressor
obesity_risk_score: MultiOutputRegressor
cholesterol_risk_score: MultiOutputRegressor

In [17]:
#Save a human-readable model summary

final_model_summary = best_models_df.copy()

final_model_summary.to_csv(
    "../outputs/metrics/final_model_selection.csv"
)

print(
    "Final model selection saved successfully."
)

#Final verification table

final_model_summary

Final model selection saved successfully.

                                      Model       MAE      RMSE        R2
diabetes_risk_score       Linear Regression  1.714473  2.170258  0.961087
hypertension_risk_score    Ridge Regression  2.018995  2.533213  0.960430
heart_disease_risk_score  Gradient Boosting  3.292623  4.178837  0.926755
obesity_risk_score        Gradient Boosting  1.267963  1.592833  0.979284
cholesterol_risk_score    Gradient Boosting  0.930187  1.173354  0.991975

# Final Model Saving Summary

Model evaluation identified the best-performing model for each health
risk score.

The final selected models are:

| Risk Score    | Selected Model    |
|-------------- |------------------ |
| Diabetes      | Linear Regression |
| Hypertension  | Ridge Regression  |
| Heart Disease | Gradient Boosting |
| Obesity       | Gradient Boosting |
| Cholesterol   | Gradient Boosting |

The selected models were saved in:

`models/final/`

The preprocessing pipeline remains saved as:

`models/preprocessing_pipeline.pkl`

The mapping between each risk score and its final model was saved as:

`models/final_model_info.pkl`

These saved models will be used in the final prediction pipeline.

No models were retrained in this notebook.